package cn.tuyucheng.taketoday.mongodb.daos;

import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.stereotype.Repository;

import cn.tuyucheng.taketoday.mongodb.models.User;

@Repository("userAutoGeneratedFieldRepository")
public interface UserRepository extends MongoRepository<User, Long> {

}
