---
##
## Vault Connection
##
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
   namespace: taketoday
   name: vault-local
spec:
   # required configuration
   # address to the Vault server.
   address: http://vault.vault.svc.cluster.local:8200
---
##
## Vault Auth
##
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
   namespace: taketoday
   name: taketoday-test
spec:
   # required configuration
   # VaultConnectionRef of the corresponding VaultConnection CustomResource.
   # If no value is specified the Operator will default to the `default` VaultConnection,
   # configured in its own Kubernetes namespace.
   vaultConnectionRef: vault-local
   # Method to use when authenticating to Vault.
   method: kubernetes
   # Mount to use when authenticating to auth method.
   mount: kubernetes
   # Kubernetes specific auth configuration, requires that the Method be set to kubernetes.
   kubernetes:
      # role to use when authenticating to Vault
      role: taketoday-test-role
      # ServiceAccount to use when authenticating to Vault
      # it is recommended to always provide a unique serviceAccount per Pod/application
      serviceAccount: vault-test-sa
---
##
## Vault-backed secret
##
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
   namespace: taketoday
   name: taketoday-test
spec:
   vaultAuthRef: taketoday-test
   mount: secrets
   type: kv-v2
   path: taketoday-test
   refreshAfter: 60s
   hmacSecretData: true
   destination:
      create: true
      name: taketoday-test
