spring:
   kafka:
      consumer:
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      producer:
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
         spring.json.value.default.type: cn.tuyucheng.taketoday.automq.User
         allow.auto.create.topics: true

cn:
   tuyucheng:
      taketoday:
         topic:
            onboarding-initiated: user-service.onboarding.initiated.v1