/*
 * This file is generated by jOOQ.
 */
package cn.tuyucheng.taketoday.jooq.jointables.public_;


import cn.tuyucheng.taketoday.jooq.jointables.public_.tables.Book;
import cn.tuyucheng.taketoday.jooq.jointables.public_.tables.Bookauthor;
import cn.tuyucheng.taketoday.jooq.jointables.public_.tables.Store;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

   /**
    * The table <code>public.Book</code>.
    */
   public static final Book BOOK = Book.BOOK;

   /**
    * The table <code>public.BookAuthor</code>.
    */
   public static final Bookauthor BOOKAUTHOR = Bookauthor.BOOKAUTHOR;

   /**
    * The table <code>public.Store</code>.
    */
   public static final Store STORE = Store.STORE;
}
